version: '3.8'

services:
  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    hostname: datanode3  # Важно: уникальное имя
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://45.156.21.217::9000  # Укажите IP вашего NameNode
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - HDFS_CONF_dfs_permissions_enabled=false
    ports:
      - "9866:9866"  # DataNode HTTP
      - "9867:9867"  # DataNode IPC
      
      
volumes:
  hadoop_datanode3:      